tf workfold /cloak "AddressManager"
tf workfold /cloak "AgentServer"
tf workfold /cloak "BrowseServer"
tf workfold /cloak "BSM"
tf workfold /cloak "ClassManager"
tf workfold /cloak "CLIServer"
tf workfold /cloak "CommCenter"
::tf workfold /cloak "Common"
tf workfold /cloak "Common.NET"
tf workfold /cloak "Communication Server"
::tf workfold /cloak "ComponentsBds2006"
tf workfold /cloak "ControlCenter"
tf workfold /cloak "CopyX"
tf workfold /cloak "CppUnit"
::tf workfold /cloak "DBAdmin"
tf workfold /cloak "DBMib"
tf workfold /cloak "DemoCD"
tf workfold /cloak "Device Manager"
tf workfold /cloak "DiscoveryServer"
tf workfold /cloak "DiscoveryServerVC"
tf workfold /cloak "doc"
tf workfold /cloak "EnterpriseLibrary"
tf workfold /cloak "ERP4ITDataProvider"
::tf workfold /cloak "EventServer"
tf workfold /cloak "FastMM4"
::tf workfold /cloak "Helper"
tf workfold /cloak "HistoryServer"
tf workfold /cloak "LayoutServer"
tf workfold /cloak "Libharu"
tf workfold /cloak "Licensing Handler"
tf workfold /cloak "LMC_ARS"
::tf workfold /cloak "log4cxx"
::tf workfold /cloak "log4net"
tf workfold /cloak "LogparserServer"
tf workfold /cloak "Message Send"
tf workfold /cloak "MibCompilation"
::tf workfold /cloak "MultiSiteServer"
tf workfold /cloak "net-snmp"
tf workfold /cloak "NetworkManager"
tf workfold /cloak "nmavail"
::tf workfold /cloak "NMDBServer"
::tf workfold /cloak "NMDBServerAssistantLayer"
tf workfold /cloak "nmhistory"
tf workfold /cloak "nmsnmp61"
::tf workfold /cloak "nmstring"
tf workfold /cloak "OpenPegasus"
tf workfold /cloak "OpenSSL"
tf workfold /cloak "OreasDll"
tf workfold /cloak "parse_build_param.bat"
tf workfold /cloak "Performance Monitor"
tf workfold /cloak "PollServer"
::tf workfold /cloak "ProcessAdmin"
::tf workfold /cloak "ProcessMonitor"
tf workfold /cloak "QoSMon"
::tf workfold /cloak "RelationServer"
tf workfold /cloak "Reporting"
::tf workfold /cloak "ReportingTypeCompression"
::tf workfold /cloak "RequestServer"
tf workfold /cloak "ResourceDll"
tf workfold /cloak "RMON Tools"
::tf workfold /cloak "ScheduleServer"
tf workfold /cloak "SCOM"
tf workfold /cloak "ServerMonitor"
tf workfold /cloak "Service Pack Installer"
tf workfold /cloak "ServiceCenter"
tf workfold /cloak "SetupImageDll"
::tf workfold /cloak "SharedBuffer"
tf workfold /cloak "SNMPv3"
::tf workfold /cloak "SQLite"
tf workfold /cloak "StatusSend"
tf workfold /cloak "SysName"
::tf workfold /cloak "TextResource"
tf workfold /cloak "tGCommon"
::tf workfold /cloak "tGProtocol"
::tf workfold /cloak "tGServerCommon"
tf workfold /cloak "TPowerDll"
tf workfold /cloak "TrapSend"
tf workfold /cloak "TrapServer"
tf workfold /cloak "UnitTests"
tf workfold /cloak "V90Reporting"
tf workfold /cloak "VMWare"
tf workfold /cloak "WebChart"
tf workfold /cloak "WebLicense"
tf workfold /cloak "WebMap"
tf workfold /cloak "WebMib"
tf workfold /cloak "WebOEM"
tf workfold /cloak "Window Spitter"
::tf workfold /cloak "xerces"